export const TOP_LEFT = 'top-left'
export const TOP_CENTER = 'top-center'
export const TOP_RIGHT = 'top-right'
export const BOTTOM_LEFT = 'bottom-left'
export const BOTTOM_CENTER = 'bottom-center'
export const BOTTOM_RIGHT = 'bottom-right'