export const URL_LOGIN = '/login';
export const URL_REGISTER= '/register';
export const URL_PROFILE = '/profile';
export const URL_USER = '/user';
export const URL_NEWS = '/news';
export const URL_MAP = '/map';
export const URL_INFO = '/info';
export const URL_CALENDAR = '/calendar';
export const URL_SCHEDULE = '/schedule';
